app:
  env: local
  port: 8888
  app_name: chatbot-backend
  app_url: http://localhost
# define log
log:
  level: info #level of log
  root_dir: ./storage/logs
  filename: app.log
  format:
  show_line: true # show the line in the code
  max_backups: 3
  max_size: 500
  max_age: 28
  compress: true
database:
  driver: postgres
  host: 14.103.165.126
  port: 5432
  database: chatbot # database name
  username: root
  password: secret
  log_mode: info # db log level
  enable_file_log_writer: true
  log_filename: sql.log
  max_idle_conns: 10
  max_open_conns: 100
google_client_id:
jwt:
  secret: 3Bde3BGEbYqtqyEUzW3ry8jKFcaPH17fRmTmqE7MDr05Lwj95uruRKrrkb44TJ4s
  jwt_ttl: 43200
  jwt_blacklist_grace_period: 10
redis:
  host: 127.0.0.1
  port: 6379
  db: 0
  password:
